# Generated by Django 3.2.2 on 2021-05-17 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenhouse', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Planter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants', models.CharField(max_length=220)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasvihuone.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasvihuone.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Soilmoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasvihuone.greenhouse')),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasvihuone.planter')),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasvihuone.greenhouse')),
            ],
        ),
    ]
